# Generated by Django 6.1 on 2026-08-15 08:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HarvestedURL',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(db_index=True, max_length=2048, unique=True)),
                ('http_status_code', models.IntegerField(blank=True, help_text='HTTP response status code (e.g., 200, 404)', null=True)),
                ('raw_content', models.TextField(help_text='Raw HTML or raw response body from the URL')),
                ('page_title', models.CharField(blank=True, default='', max_length=512)),
                ('meta_description', models.TextField(blank=True, default='')),
                ('cleaned_text', models.TextField(blank=True, default='', help_text='Cleaned, human-readable text extracted from HTML')),
                ('metadata_json', models.JSONField(blank=True, default=dict, help_text='Response headers, content type, scrape latency, etc.')),
                ('executive_details', models.JSONField(blank=True, default=list, help_text='Extracted person names, roles, executive bios, and leadership information')),
                ('is_indexed', models.BooleanField(db_index=True, default=False, help_text='Whether this URL has been ingested into FAISS vector database')),
                ('indexed_at', models.DateTimeField(blank=True, null=True)),
                ('total_chunks', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Harvested URL',
                'verbose_name_plural': 'Harvested URLs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ScrapingLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_id', models.CharField(db_index=True, max_length=64)),
                ('url', models.URLField(max_length=2048)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('SUCCESS', 'Success'), ('FAILED', 'Failed'), ('SKIPPED', 'Skipped')], default='PENDING', max_length=32)),
                ('http_status', models.IntegerField(blank=True, null=True)),
                ('message', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='URLChunk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chunk_index', models.IntegerField()),
                ('chunk_text', models.TextField()),
                ('chunk_hash', models.CharField(blank=True, default='', max_length=64)),
                ('vector_id', models.IntegerField(blank=True, help_text='Index ID in the FAISS vector database', null=True)),
                ('has_person_info', models.BooleanField(default=False, help_text='Flag indicating executive or person entity present')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('harvested_url', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chunks', to='harvester.harvestedurl')),
            ],
            options={
                'verbose_name': 'URL Chunk',
                'verbose_name_plural': 'URL Chunks',
                'ordering': ['harvested_url', 'chunk_index'],
                'unique_together': {('harvested_url', 'chunk_index')},
            },
        ),
    ]
